import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <p className="text-center text-9xl text-gray-500 py-4">
          EMMÉ
        </p>
          <nav>
            <ul className="flex space-x-4 p-4 bg-gray-100 justify-center">
              <li>
                <a href="/" className="text-blue-500 hover:underline">
                  Forside
                </a>
              </li>
              <li>
                <a href="/frisoer" className="text-blue-500 hover:underline">
                  Book Frisør
                </a>
              </li>
              <li>
                <a href="/kosmetikker" className="text-blue-500 hover:underline">
                  Book Kosmetikker
                </a>
              </li>
              <li>
                <a href="/about" className="text-blue-500 hover:underline">
                  Om os
                </a>
              </li>
            </ul>
          </nav>
          {children}
        </body>
    </html>
  );
}
